### ISSUE TITLE
selected item in dashboard menu

### ISSUE THREAD

**Issue by samanthajlee2** [rcos/venue#163]
when selecting an item on the dashboard menu, the item above it is momentarily highlighted

this happens after an event/course is clicked

**Comment by kmcnellis** [comment]
I believe this is fixed in feature-refactor-css

**Comment by samanthajlee2** [comment]
It looks to me like the bug is still there. It's a very minor thing, not worth spending time on. Just wanted to document it.
